name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # BEGIN Dependencies
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.5"
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/cache@v2
        with:
          path: |
            vendor/bundle
            ~/.cache/pip
            ~/.npm
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}-py-${{ hashFiles('**/requirements.txt') }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}-py-${{ hashFiles('**/requirements.txt') }}-node-
            ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}-py--node-
            ${{ runner.os }}-gems-
      - name: Install dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          pip install -r requirements.txt
          npm install
      # END Dependencies

      - name: Build Site
        run: |
          gem install bundler
          python -m pip install --upgrade pip
          pip install requests ephemeris
          export PATH=/home/runner/.local/bin:$PATH
          make annotate ACTIVATE_ENV=pwd
          npm install
          make rebuild-search-index ACTIVATE_ENV=pwd
          cat metadata/swagger.yaml | python bin/yaml2json.py > api/swagger.json
          JEKYLL_ENV=production bundle exec jekyll build --strict_front_matter -d _site/training-material
        env:
          GTN_FORK: ${{ github.repository_owner }}

      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site/training-material/
          publish_branch: gh-pages
